#### Installation of ArgoCD Helm Chart and other resources including the general helm charts ####
namespace: argocd
helmCharts:
- name: argo-cd
  repo: https://argoproj.github.io/argo-helm
  version: 5.53.5
  releaseName: argocd
  namespace: argocd
  valuesFile: base/values.yaml 

resources:
- base/namespace.yaml                        # ArgoCD Namespace
- base/repository-registeration.yaml         # GitHub Repository Registeration
- base/application-argocd.yaml               # Managing Argo with Argo (App of Apps concept) using ArgoCD Application definition
- base/git-generator-directory-charts.yaml.  # Helm Chart installation with ApplicationSet