# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: guestbook-ui
# spec:
#   replicas: 1
#   revisionHistoryLimit: 3
#   selector:
#     matchLabels:
#       app: guestbook-ui
#   template:
#     metadata:
#       labels:
#         app: guestbook-ui
#     spec:
#       containers:
#       - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
#         name: guestbook-ui
#         ports:
#         - containerPort: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: guestbook-ui
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 80
#     targetPort: 80
#   selector:
#     app: guestbook-ui
---
#namePrefix: kustomize-

resources:
- https://github.com/argoproj/argo-workflows/releases/download/v3.4.0/namespace-install.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization