
#### ArgoCD Helm Chart values ####
# Argo-CD Helm chart values COULD be changed according to the env/cluster
# The Ingress host name HAS TO be changed according to the env/cluster
server:
  replicas: 3
  config:
    # https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/
    kustomize.buildOptions: --enable-helm
    timeout.reconcilation: 20s